name: ci

on:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Go Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: go fmt
        run: go fmt ./...

      - name: go vet
        run: go vet -v  ./...

      - name: go test
        run: go test -v ./...
